### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by max-sixty** [nov1n/kubernetes-workflow#73]
This looks like a compelling concept, but hasn't been changed in a while. 

Is there any ongoing development / running workloads on this?

**Comment by borismattijssen** [comment]
Hey Maximilian, 

@nov1n and I worked on this last year as part of our bachelor thesis for the company [Nerdalize](github.com/nerdalize). The repo contains a working PoC, that relies heavily on Kubernetes' ThirdPartyResources. I know that ThirdPartyResources have matured over the past year, but haven't  really digged into it yet. The project will need some refactoring to make it work with the new TPR API. This will make it a lot more stable, since we don't have to hack around the TPR bugs anymore. 

Are you feeling like contributing?

**Comment by max-sixty** [comment]
Thanks for the update @borismattijssen 

Our end: we're at a really early stage of reviewing options for a scalable workflow scheduler with native dependencies, and some folks at Google pointed me towards this. So we're some way from contributing to one of the libraries at this point, though that may change.
